#! /bin/bash

VV_OPTS="-f -a --spice-shared-dir=Public"
IMG_DIR=~/vmm/images
KEEP=

usage() {
  echo "${0##*/} [options] <name>"
  echo "    -d delete name"
  echo "    -h this screen"
  echo "    -k keep previous snapshot"
  echo "    -m run virt-manager"
  exit
}

delete() {
  read -p "$1 을 정말 삭제하시겠습니까? [Ny] " ANS
  [ x$ANS = xy ] || [ x$ANS = xY ] && virsh undefine $1 --remove-all-storage --nvram
  exit
}

while getopts "d:hkms:" opt; do
    case $opt in
        d) delete $OPTARG ;;
        h) usage ;;
        k) KEEP=on ;;
        m) exec virt-manager ;;
        s) SHARE="$OPTARG" ;;
    esac
done
shift $(( OPTIND - 1 ))
name=$1

cd $IMG_DIR

[ -f $name.qcow2.orig ] || exit

if virsh list | sed 1,2d | grep running | grep -q $name; then
  virt-viewer $VV_OPTS $name &
else
  [ -z "$KEEP" ] && qemu-img create -F qcow2 -f qcow2 -b $name.qcow2.orig $name.qcow2 || true
  [ $? -eq 0 ] &&
  virsh start $name &&
  virt-viewer $VV_OPTS $name &
fi
